name: Run Python Script

on:
  schedule:
    - cron: '58 * * * *'  # Ejecutar cada hora a los 58 minutos
  workflow_dispatch:  # Permite ejecución manual desde la UI de GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script with environment variables
        run: python sg.py  # Reemplaza 'script.py' con el nombre de tu script
        env:
          bot_token: ${{ secrets.bot_token }}
          chat_id: ${{ secrets.chat_id }}
          user_agent: ${{ secrets.user_agent }}
          cookie: ${{ secrets.cookie }}
