name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'    # 00:00
    - cron: '58 0 * * *'    # 00:58
    - cron: '56 1 * * *'    # 01:56
    - cron: '54 2 * * *'    # 02:54
    - cron: '52 3 * * *'    # 03:52
    - cron: '50 4 * * *'    # 04:50
    - cron: '48 5 * * *'    # 05:48
    - cron: '46 6 * * *'    # 06:46
    - cron: '44 7 * * *'    # 07:44
    - cron: '42 8 * * *'    # 08:42
    - cron: '40 9 * * *'    # 09:40
    - cron: '38 10 * * *'   # 10:38
    - cron: '36 11 * * *'   # 11:36
    - cron: '34 12 * * *'   # 12:34
    - cron: '32 13 * * *'   # 13:32
    - cron: '30 14 * * *'   # 14:30
    - cron: '28 15 * * *'   # 15:28
    - cron: '26 16 * * *'   # 16:26
    - cron: '24 17 * * *'   # 17:24
    - cron: '22 18 * * *'   # 18:22
    - cron: '20 19 * * *'   # 19:20
    - cron: '18 20 * * *'   # 20:18
    - cron: '16 21 * * *'   # 21:16
    - cron: '14 22 * * *'   # 22:14
    - cron: '12 23 * * *'   # 23:12
  workflow_dispatch:  # Permite ejecución manual desde la UI de GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script with environment variables
        run: python sg.py  # Reemplaza 'script.py' con el nombre de tu script
        env:
          bot_token: ${{ secrets.bot_token }}
          chat_id: ${{ secrets.chat_id }}
          user_agent: ${{ secrets.user_agent }}
          cookie: ${{ secrets.cookie }}
